import type { JournalEntry } from '@/features/accounting/domain/types/journal-entry';

export const INITIAL_MOCK_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'je-1',
    name: 'الفات/2026/00003',
    date: '2026-09-07',
    accountingDate: '2026-09-07',
    partnerName: 'علي بن علي',
    reference: 'S00003',
    journalId: 'sales',
    journalName: 'المبيعات',
    total: 258.75,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-1-1',
        accountId: '121000 حساب مدين',
        partnerName: 'علي بن علي',
        name: 'S00003 - مبيعات منتجات وخدمات',
        debit: 258.75,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-1-2',
        accountId: '400000 حساب إيرادات المبيعات',
        partnerName: 'علي بن علي',
        name: 'إيراد المبيعات',
        debit: 0.0,
        credit: 225.0,
        taxGrids: 'ضريبة القيمة المضافة 15%',
      },
      {
        id: 'ji-1-3',
        accountId: '220000 ضريبة القيمة المضافة المحصلة',
        partnerName: 'علي بن علي',
        name: 'ضريبة مخرجات 15%',
        debit: 0.0,
        credit: 33.75,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-2',
    name: 'الفات/2026/00002',
    date: '2026-09-07',
    accountingDate: '2026-09-07',
    partnerName: 'علي بن علي',
    reference: 'S00003',
    journalId: 'sales',
    journalName: 'المبيعات',
    total: 603.75,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-2-1',
        accountId: '121000 حساب مدين',
        partnerName: 'علي بن علي',
        name: 'S00003 - فاتورة رقم 2',
        debit: 603.75,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-2-2',
        accountId: '400000 حساب إيرادات المبيعات',
        partnerName: 'علي بن علي',
        name: 'إيراد المبيعات',
        debit: 0.0,
        credit: 525.0,
        taxGrids: 'ضريبة القيمة المضافة 15%',
      },
      {
        id: 'ji-2-3',
        accountId: '220000 ضريبة القيمة المضافة المحصلة',
        partnerName: 'علي بن علي',
        name: 'ضريبة مخرجات 15%',
        debit: 0.0,
        credit: 78.75,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-3',
    name: 'المتف/2026/09/0004',
    date: '2026-09-06',
    accountingDate: '2026-09-06',
    partnerName: '',
    reference: '',
    journalId: 'misc',
    journalName: 'عمليات متنوعة',
    total: 1150.0,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    nonModifiableEncryption: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-3-1',
        accountId: '121000 حساب مدين',
        partnerName: 'علي بن علي',
        name: 'التحويل إلى 211000 حساب الدائن',
        debit: 0.0,
        credit: 1150.0,
        taxGrids: '',
      },
      {
        id: 'ji-3-2',
        accountId: '211000 حساب الدائن',
        partnerName: 'علي بن علي',
        name: 'التحويل من 121000 حساب مدين',
        debit: 1150.0,
        credit: 0.0,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-4',
    name: 'المتف/2026/09/0003',
    date: '2026-09-06',
    accountingDate: '2026-09-06',
    partnerName: '',
    reference: '',
    journalId: 'misc',
    journalName: 'عمليات متنوعة',
    total: 1150.0,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-4-1',
        accountId: '121000 حساب مدين',
        partnerName: 'علي بن علي',
        name: 'تسوية رصيد حساب',
        debit: 0.0,
        credit: 1150.0,
        taxGrids: '',
      },
      {
        id: 'ji-4-2',
        accountId: '211000 حساب الدائن',
        partnerName: 'علي بن علي',
        name: 'تسوية قيد عكسي',
        debit: 1150.0,
        credit: 0.0,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-5',
    name: 'المتف/2026/09/0002',
    date: '2026-09-05',
    accountingDate: '2026-09-05',
    partnerName: '',
    reference: '',
    journalId: 'misc',
    journalName: 'عمليات متنوعة',
    total: 10000.0,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-5-1',
        accountId: '101000 الصندوق الرئيسي',
        partnerName: '',
        name: 'إيداع نقدي بالخزينة',
        debit: 10000.0,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-5-2',
        accountId: '102000 البنك الأهلي السعودي',
        partnerName: '',
        name: 'سحب نقدي من البنك',
        debit: 0.0,
        credit: 10000.0,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-6',
    name: 'المتف/2026/09/0001',
    date: '2026-09-05',
    accountingDate: '2026-09-05',
    partnerName: '',
    reference: '',
    journalId: 'misc',
    journalName: 'عمليات متنوعة',
    total: 10000.0,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-6-1',
        accountId: '102000 البنك الأهلي السعودي',
        partnerName: '',
        name: 'تحويل بين الحسابات البنكية',
        debit: 10000.0,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-6-2',
        accountId: '102100 مصرف الراجحي',
        partnerName: '',
        name: 'تحويل بين الحسابات البنكية',
        debit: 0.0,
        credit: 10000.0,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-7',
    name: 'STJ/2026/09/0001',
    date: '2026-09-05',
    accountingDate: '2026-09-05',
    partnerName: '',
    reference: 'Stock Closing',
    journalId: 'stock',
    journalName: 'تقسيم المخزون',
    total: 28949.43,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-7-1',
        accountId: '140000 مخزون بضاعة تامة الصنع',
        partnerName: '',
        name: 'Stock Closing - إغلاق مخزون سبتمبر',
        debit: 28949.43,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-7-2',
        accountId: '500000 تكلفة البضاعة المباعة',
        partnerName: '',
        name: 'Stock Valuation Adjustment',
        debit: 0.0,
        credit: 28949.43,
        taxGrids: '',
      },
    ],
  },
  {
    id: 'je-8',
    name: 'الفات/2026/00001',
    date: '2026-09-03',
    accountingDate: '2026-09-03',
    partnerName: 'علي بن علي',
    reference: '',
    journalId: 'sales',
    journalName: 'المبيعات',
    total: 1150.0,
    state: 'posted',
    autoPost: false,
    fiscalPosition: '',
    internalNotes: '',
    items: [
      {
        id: 'ji-8-1',
        accountId: '121000 حساب مدين',
        partnerName: 'علي بن علي',
        name: 'فاتورة مبيعات استشارات',
        debit: 1150.0,
        credit: 0.0,
        taxGrids: '',
      },
      {
        id: 'ji-8-2',
        accountId: '400000 حساب إيرادات المبيعات',
        partnerName: 'علي بن علي',
        name: 'إيراد الخدمات الاستشارية',
        debit: 0.0,
        credit: 1000.0,
        taxGrids: 'ضريبة القيمة المضافة 15%',
      },
      {
        id: 'ji-8-3',
        accountId: '220000 ضريبة القيمة المضافة المحصلة',
        partnerName: 'علي بن علي',
        name: 'ضريبة مخرجات 15%',
        debit: 0.0,
        credit: 150.0,
        taxGrids: '',
      },
    ],
  },
];
