import type { AccountingProduct } from '@/features/accounting/domain/types/accounting-product';

export const INITIAL_MOCK_PRODUCTS: AccountingProduct[] = [
  {
    id: '38',
    name: 'أجهزة نقاط البيع الذكية (POS Terminal)',
    canBeSold: true,
    canBePurchased: true,
    type: 'product',
    invoicingPolicy: 'order',
    uom: 'وحدة',
    purchaseUom: 'وحدة',
    salesPrice: 3200,
    customerTaxes: ['15%'],
    cost: 2100,
    category: 'إلكترونيات وأجهزة',
    internalReference: 'POS-TERM-01',
    barcode: '628100098765',
    avatarColor: '#2563eb',
    incomeAccount: '400000 إيرادات مبيعات المنتجات',
    expenseAccount: '600000 تكلفة البضاعة المباعة',
    salesCount: 14,
    purchasesCount: 20,
    onHandQty: 6,
  },
  {
    id: '39',
    name: 'خدمات استشارية محاسبية وتدقيق مالي',
    canBeSold: true,
    canBePurchased: false,
    type: 'service',
    invoicingPolicy: 'order',
    uom: 'ساعة',
    purchaseUom: 'ساعة',
    salesPrice: 1500,
    customerTaxes: ['15%'],
    cost: 500,
    category: 'خدمات استشارية',
    internalReference: 'SRV-ACC-01',
    avatarColor: '#7c3aed',
    incomeAccount: '400000 إيرادات الخدمات والاستشارات',
    expenseAccount: '600000 مصروفات الاستشارات',
    salesCount: 28,
    purchasesCount: 0,
    onHandQty: 0,
  },
  {
    id: '40',
    name: 'اشتراك سنوي في المنظومة السحابية ERP',
    canBeSold: true,
    canBePurchased: false,
    type: 'service',
    invoicingPolicy: 'order',
    uom: 'اشتراك سنوي',
    purchaseUom: 'اشتراك سنوي',
    salesPrice: 12000,
    customerTaxes: ['15%'],
    cost: 3000,
    category: 'برمجيات وسحابة',
    internalReference: 'SFT-ERP-YR',
    avatarColor: '#059669',
    incomeAccount: '400000 إيرادات الاشتراكات والبرمجيات',
    expenseAccount: '600000 تكلفة السيرفرات',
    salesCount: 8,
    purchasesCount: 0,
    onHandQty: 0,
  },
  {
    id: '41',
    name: 'طابعة فواتير حرارية (Thermal Printer)',
    canBeSold: true,
    canBePurchased: true,
    type: 'product',
    invoicingPolicy: 'delivery',
    uom: 'قطعة',
    purchaseUom: 'قطعة',
    salesPrice: 450,
    customerTaxes: ['15%'],
    cost: 280,
    category: 'ملحقات وأجهزة',
    internalReference: 'PRN-THM-80',
    barcode: '628100054321',
    avatarColor: '#d97706',
    incomeAccount: '400000 إيرادات مبيعات المنتجات',
    expenseAccount: '600000 تكلفة البضاعة المباعة',
    salesCount: 45,
    purchasesCount: 50,
    onHandQty: 5,
  },
];
