import type { CustomerPayment } from '@/features/accounting/domain/types/customer-payment';

export const INITIAL_MOCK_PAYMENTS: CustomerPayment[] = [
  {
    id: '1',
    name: 'CUST.IN/2024/00001',
    paymentType: 'inbound',
    partnerType: 'customer',
    partnerId: 'cust-2',
    partnerName: 'شركة الأمل للتجارة',
    amount: 11040,
    currency: 'SAR',
    paymentDate: '2024-05-11',
    memo: 'سداد كامل لفاتورة INV/2024/00002',
    journalId: 'j-3',
    journalName: 'البنك (الراجحي)',
    paymentMethodLine: 'تحويل بنكي مباشر',
    state: 'posted',
    matchedInvoicesCount: 1,
  },
  {
    id: '2',
    name: 'CUST.IN/2024/00002',
    paymentType: 'inbound',
    partnerType: 'customer',
    partnerId: 'cust-3',
    partnerName: 'مؤسسة النور الحديثة',
    amount: 6900,
    currency: 'SAR',
    paymentDate: '2024-05-02',
    memo: 'دفعة مقدمة 50% لفاتورة INV/2024/00001',
    journalId: 'j-3',
    journalName: 'البنك (الراجحي)',
    paymentMethodLine: 'تحويل بنكي مباشر',
    state: 'posted',
    matchedInvoicesCount: 1,
  },
  {
    id: '3',
    name: 'CUST.IN/2024/00003',
    paymentType: 'inbound',
    partnerType: 'customer',
    partnerId: 'cust-1',
    partnerName: 'علي بن علي',
    amount: 3000,
    currency: 'SAR',
    paymentDate: '2024-05-13',
    memo: 'دفعة نقدية تحت الحساب',
    journalId: 'j-4',
    journalName: 'الخزينة النقدية الرئيسية',
    paymentMethodLine: 'يدوي (نقدي)',
    state: 'posted',
    matchedInvoicesCount: 0,
  },
];
