import type { Currency } from '@/features/accounting/domain/types/currency';

export const MOCK_CURRENCIES: Currency[] = [
  {
    id: 'SAR',
    code: 'SAR',
    nameAr: 'Saudi riyal',
    symbol: 'SR',
    currencyUnit: 'ريال سعودي',
    currencySubunit: 'هللة',
    symbolPosition: 'before',
    active: true,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '1 سبتمبر',
    unitPerBaseRate: 0.007143,
    rates: [
      {
        id: 'r-sar-1',
        date: '1 سبتمبر',
        unitPerBase: 0.007142857143,
        basePerUnit: 140.0,
      },
    ],
  },
  {
    id: 'USD',
    code: 'USD',
    nameAr: 'United States dollar',
    symbol: '$',
    currencyUnit: 'دولار',
    currencySubunit: 'سنتات',
    symbolPosition: 'before',
    active: true,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '1 سبتمبر',
    unitPerBaseRate: 0.001887,
    rates: [
      {
        id: 'r-usd-1',
        date: '1 سبتمبر',
        unitPerBase: 0.001886792453,
        basePerUnit: 530.000000000001,
      },
    ],
  },
  {
    id: 'YER',
    code: 'YER',
    nameAr: 'Yemeni rial',
    symbol: 'ريال',
    currencyUnit: 'Rial',
    currencySubunit: 'فلس',
    symbolPosition: 'after',
    active: true,
    isBaseCurrency: true,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'AED',
    code: 'AED',
    nameAr: 'United Arab Emirates dirham',
    symbol: 'AED',
    currencyUnit: 'درهم إماراتي',
    currencySubunit: 'فلس',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'AFN',
    code: 'AFN',
    nameAr: 'Afghan afghani',
    symbol: 'Afs',
    currencyUnit: 'أفغاني',
    currencySubunit: 'بول',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'ALL',
    code: 'ALL',
    nameAr: 'Albanian lek',
    symbol: 'L',
    currencyUnit: 'ليك',
    currencySubunit: 'قنداركة',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'AMD',
    code: 'AMD',
    nameAr: 'Armenian dram',
    symbol: 'դր.',
    currencyUnit: 'درام',
    currencySubunit: 'لوما',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'ANG',
    code: 'ANG',
    nameAr: 'Netherlands Antillean guilder',
    symbol: 'ƒ',
    currencyUnit: 'غيلدر',
    currencySubunit: 'سنت',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'AOA',
    code: 'AOA',
    nameAr: 'Angolan kwanza',
    symbol: 'Kz',
    currencyUnit: 'كوانزا',
    currencySubunit: 'سينتيمو',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'ARS',
    code: 'ARS',
    nameAr: 'Argentine peso',
    symbol: '$',
    currencyUnit: 'بيزو',
    currencySubunit: 'سينتافو',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'EUR',
    code: 'EUR',
    nameAr: 'Euro',
    symbol: '€',
    currencyUnit: 'يورو',
    currencySubunit: 'سنت',
    symbolPosition: 'before',
    active: true,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '1 سبتمبر',
    unitPerBaseRate: 0.00172,
    rates: [
      {
        id: 'r-eur-1',
        date: '1 سبتمبر',
        unitPerBase: 0.00172,
        basePerUnit: 581.3953488,
      },
    ],
  },
  {
    id: 'GBP',
    code: 'GBP',
    nameAr: 'British pound',
    symbol: '£',
    currencyUnit: 'جنيه إسترليني',
    currencySubunit: 'بنس',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'KWD',
    code: 'KWD',
    nameAr: 'Kuwaiti dinar',
    symbol: 'KD',
    currencyUnit: 'دينار كويتي',
    currencySubunit: 'فلس',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.001,
    decimalPlaces: 3,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'QAR',
    code: 'QAR',
    nameAr: 'Qatari riyal',
    symbol: 'QR',
    currencyUnit: 'ريال قطري',
    currencySubunit: 'درهم',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'BHD',
    code: 'BHD',
    nameAr: 'Bahraini dinar',
    symbol: 'BD',
    currencyUnit: 'دينار بحريني',
    currencySubunit: 'فلس',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.001,
    decimalPlaces: 3,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'OMR',
    code: 'OMR',
    nameAr: 'Omani rial',
    symbol: 'RO',
    currencyUnit: 'ريال عماني',
    currencySubunit: 'بيسة',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.001,
    decimalPlaces: 3,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'EGP',
    code: 'EGP',
    nameAr: 'Egyptian pound',
    symbol: 'E£',
    currencyUnit: 'جنيه مصري',
    currencySubunit: 'قرش',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'JOD',
    code: 'JOD',
    nameAr: 'Jordanian dinar',
    symbol: 'JD',
    currencyUnit: 'دينار أردني',
    currencySubunit: 'قرش',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.001,
    decimalPlaces: 3,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'TRY',
    code: 'TRY',
    nameAr: 'Turkish lira',
    symbol: '₺',
    currencyUnit: 'ليرة تركية',
    currencySubunit: 'قروش',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'CNY',
    code: 'CNY',
    nameAr: 'Chinese yuan',
    symbol: '¥',
    currencyUnit: 'يوان صيني',
    currencySubunit: 'جياو',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 0.01,
    decimalPlaces: 2,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
  {
    id: 'JPY',
    code: 'JPY',
    nameAr: 'Japanese yen',
    symbol: '¥',
    currencyUnit: 'ين ياباني',
    currencySubunit: 'سن',
    symbolPosition: 'before',
    active: false,
    roundingFactor: 1.0,
    decimalPlaces: 0,
    lastUpdated: '',
    unitPerBaseRate: 1.0,
    rates: [],
  },
];
