import type { VendorRefund } from '@/features/accounting/domain/types/vendor-refund';

export const INITIAL_MOCK_VENDOR_REFUNDS: VendorRefund[] = [
  {
    id: '7',
    name: 'RBILL/2024/00007',
    vendorId: 'vend-1',
    vendorName: 'مؤسسة التقنية المتقدمة',
    refundReference: 'SUP-REF-0012',
    refundDate: '2024-05-15',
    accountingDate: '2024-05-15',
    dueDate: '2024-05-29',
    originalBillName: 'BILL/2024/00006',
    journalId: 'j-2',
    journalName: 'المشتريات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'paid',
    reason: 'إرجاع جهاز نقطة بيع تالف واسترداد قيمته من المورد',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'vr-line-1',
        name: 'توريد أجهزة نقاط بيع ذكية (مرتجع جهاز تالف)',
        accountId: 'Expenses 600000',
        quantity: 1,
        uom: 'وحدة',
        priceUnit: 2100,
        taxes: ['15%'],
        priceSubtotal: 2100,
      },
    ],
    amountUntaxed: 2100,
    amountTax: 315,
    amountTotal: 2415,
    amountDue: 0,
    terms: 'تم خصم قيمة الإشعار من الرصيد المستحق للمورد.',
  },
  {
    id: '8',
    name: 'RBILL/2024/00008',
    vendorId: 'vend-2',
    vendorName: 'شركة السحابة الرقمية للاتصالات',
    refundReference: 'CLOUD-CREDIT-55',
    refundDate: '2024-05-16',
    accountingDate: '2024-05-16',
    dueDate: '2024-05-30',
    originalBillName: 'BILL/2024/00007',
    journalId: 'j-2',
    journalName: 'المشتريات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'not_paid',
    reason: 'خصم تعويضي عن انقطاع الخدمة',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'vr-line-2',
        name: 'خصم تعويضي عن ساعات التوقف',
        accountId: 'Expenses 600000',
        quantity: 1,
        uom: 'بند',
        priceUnit: 500,
        taxes: ['15%'],
        priceSubtotal: 500,
      },
    ],
    amountUntaxed: 500,
    amountTax: 75,
    amountTotal: 575,
    amountDue: 575,
    terms: 'سيتم التسوية في الدفعة القادمة.',
  },
];
