import type { CustomerInvoice } from '@/features/accounting/domain/types/customer-invoice';

export const INITIAL_MOCK_INVOICES: CustomerInvoice[] = [
  {
    id: '3',
    name: 'INV/2024/00003',
    customerId: 'cust-1',
    customerName: 'علي بن علي',
    invoiceDate: '2024-05-12',
    dueDate: '2024-05-26',
    deliveryDate: '2024-05-12',
    paymentReference: 'INV/2024/00003',
    journalId: 'j-1',
    journalName: 'المبيعات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'not_paid',
    salesperson: 'أحمد سعيد',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'line-1',
        name: 'خدمات استشارية محاسبية وتدقيق',
        accountId: 'Product Sales 400000',
        quantity: 2,
        uom: 'ساعة',
        priceUnit: 1500,
        taxes: ['15%'],
        priceSubtotal: 3000,
      },
      {
        id: 'line-2',
        name: 'إعداد ومراجعة تقارير الزكاة والضريبة',
        accountId: 'Product Sales 400000',
        quantity: 1,
        uom: 'وحدة',
        priceUnit: 2500,
        taxes: ['15%'],
        priceSubtotal: 2500,
      },
    ],
    amountUntaxed: 5500,
    amountTax: 825,
    amountTotal: 6325,
    amountDue: 6325,
    terms: 'يرجى سداد الفاتورة خلال 14 يوماً من تاريخ الإصدار عبر التحويل البنكي لحساب الراجحي.',
    electronicInvoiceStatus: 'signed',
  },
  {
    id: '2',
    name: 'INV/2024/00002',
    customerId: 'cust-2',
    customerName: 'شركة الأمل للتجارة',
    invoiceDate: '2024-05-10',
    dueDate: '2024-05-24',
    deliveryDate: '2024-05-10',
    paymentReference: 'INV/2024/00002',
    journalId: 'j-1',
    journalName: 'المبيعات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'paid',
    salesperson: 'محمد عبدالله',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'line-3',
        name: 'توريد وتركيب أجهزة نقاط البيع',
        accountId: 'Product Sales 400000',
        quantity: 3,
        uom: 'جهاز',
        priceUnit: 3200,
        taxes: ['15%'],
        priceSubtotal: 9600,
      },
    ],
    amountUntaxed: 9600,
    amountTax: 1440,
    amountTotal: 11040,
    amountDue: 0,
    terms: 'تم سداد المبلغ بالكامل.',
    electronicInvoiceStatus: 'sent',
  },
  {
    id: '1',
    name: 'INV/2024/00001',
    customerId: 'cust-3',
    customerName: 'مؤسسة النور الحديثة',
    invoiceDate: '2024-05-01',
    dueDate: '2024-05-15',
    deliveryDate: '2024-05-01',
    paymentReference: 'INV/2024/00001',
    journalId: 'j-1',
    journalName: 'المبيعات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'partial',
    salesperson: 'أحمد سعيد',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'line-4',
        name: 'اشتراك سنوي في المنظومة السحابية',
        accountId: 'Product Sales 400000',
        quantity: 1,
        uom: 'اشتراك',
        priceUnit: 12000,
        taxes: ['15%'],
        priceSubtotal: 12000,
      },
    ],
    amountUntaxed: 12000,
    amountTax: 1800,
    amountTotal: 13800,
    amountDue: 6900,
    terms: 'دفعة أولى 50% تم استلامها.',
    electronicInvoiceStatus: 'signed',
  },
];
