import type { CustomerCreditNote } from '@/features/accounting/domain/types/customer-credit-note';

export const INITIAL_MOCK_CREDIT_NOTES: CustomerCreditNote[] = [
  {
    id: '4',
    name: 'RINV/2024/00004',
    customerId: 'cust-1',
    customerName: 'علي بن علي',
    creditNoteDate: '2024-05-14',
    dueDate: '2024-05-28',
    reason: 'إرجاع جزء من خدمات الاستشارات وتعديل نطاق العمل',
    paymentReference: 'RINV/2024/00004',
    originalInvoiceId: '3',
    originalInvoiceName: 'INV/2024/00003',
    journalId: 'j-1',
    journalName: 'المبيعات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'paid',
    salesperson: 'أحمد سعيد',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'cn-line-1',
        name: 'خدمات استشارية محاسبية (تعديل ساعات)',
        accountId: 'Product Sales 400000',
        quantity: 1,
        uom: 'ساعة',
        priceUnit: 1500,
        taxes: ['15%'],
        priceSubtotal: 1500,
      },
    ],
    amountUntaxed: 1500,
    amountTax: 225,
    amountTotal: 1725,
    amountDue: 0,
    terms: 'تمت تسوية الإشعار الدائن مع حساب العميل.',
    electronicInvoiceStatus: 'signed',
  },
  {
    id: '5',
    name: 'RINV/2024/00005',
    customerId: 'cust-2',
    customerName: 'شركة الأمل للتجارة',
    creditNoteDate: '2024-05-15',
    dueDate: '2024-05-29',
    reason: 'خصم تجاري ممنوح بعد البيع',
    paymentReference: 'RINV/2024/00005',
    originalInvoiceId: '2',
    originalInvoiceName: 'INV/2024/00002',
    journalId: 'j-1',
    journalName: 'المبيعات',
    currency: 'SAR',
    state: 'posted',
    paymentState: 'not_paid',
    salesperson: 'محمد عبدالله',
    fiscalPosition: 'الوضع الافتراضي',
    lines: [
      {
        id: 'cn-line-2',
        name: 'خصم إضافي على أجهزة نقاط البيع',
        accountId: 'Product Sales 400000',
        quantity: 1,
        uom: 'بند',
        priceUnit: 800,
        taxes: ['15%'],
        priceSubtotal: 800,
      },
    ],
    amountUntaxed: 800,
    amountTax: 120,
    amountTotal: 920,
    amountDue: 920,
    terms: 'سيتم خصم المبلغ من الفاتورة القادمة.',
    electronicInvoiceStatus: 'sent',
  },
];
