export const CHECKPOINT_GEO_DEBOUNCE_MS = 450;
export const CHECKPOINT_GEO_MIN_QUERY_LEN = 2;

export const CHECKPOINT_RADIUS_MIN_METERS = 5;
export const CHECKPOINT_RADIUS_MAX_METERS = 2000;
export const CHECKPOINT_RADIUS_STEP_METERS = 1;
